# -*- coding: utf-8 -*-
"""fally2.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1hsvNsZXTDqPtj9DrqA6A4ainOWwbXPcL
"""

import os
import zipfile

zip_file_path = "/content/fall down.zip"
extraction_path = "/content/"

with zipfile.ZipFile(zip_file_path, "r") as zip_ref:
    zip_ref.extractall(extraction_path)

print(f"'{zip_file_path}' extracted to '{extraction_path}'")

# List the contents of the extracted folder to verify
extracted_folder_name = (
    "fall down mobile"  # Based on common practice of zip files containing a root folder
)
if os.path.exists(os.path.join(extraction_path, extracted_folder_name)):
    print(f"Contents of '/content/{extracted_folder_name}':")
    for root, dirs, files in os.walk(
        os.path.join(extraction_path, extracted_folder_name)
    ):
        for name in files:
            print(os.path.join(root, name))
        for name in dirs:
            print(os.path.join(root, name))
else:
    print(
        "Could not find 'fall down mobile' folder. Listing all contents in /content/:"
    )
    print(os.listdir(extraction_path))

from __future__ import annotations

import json
from pathlib import Path

import joblib
import matplotlib.pyplot as plt
import numpy as np
from sklearn.metrics import accuracy_score, classification_report, confusion_matrix
from sklearn.model_selection import train_test_split
from tqdm import tqdm
from xgboost import XGBClassifier

try:
    from google.colab import drive  # type: ignore

    IN_COLAB = True
except Exception:
    drive = None
    IN_COLAB = False


# =========================
# Colab setup
# =========================
def prepare_colab_environment() -> None:
    if not IN_COLAB:
        return

    try:
        drive.mount("/content/drive")
    except Exception:
        pass


if IN_COLAB:
    DATASET_ROOT = Path("/content/dataset/fall down mobile")
    OUTPUT_DIR = Path("/content/drive/MyDrive/fally_artifacts")
else:
    BASE_DIR = Path(__file__).resolve().parent
    DATASET_ROOT = BASE_DIR / "dataset" / "fall down mobile"
    OUTPUT_DIR = BASE_DIR / "artifacts"

WINDOW_SIZE = 32
OVERLAP = 16
RANDOM_STATE = 42


# =========================
# Read dataset
# =========================
def process_json_file(file_path: Path):
    try:
        with file_path.open("r", encoding="utf-8") as file:
            payload = json.load(file)
    except Exception:
        return None

    sensors = payload.get("sensors", [])
    if not sensors:
        return None

    rows = []
    for sample in sensors:
        accelerometer = sample.get("accelerometer", {})
        gyroscope = sample.get("gyroscope", {})
        rows.append(
            [
                accelerometer.get("x", np.nan),
                accelerometer.get("y", np.nan),
                accelerometer.get("z", np.nan),
                gyroscope.get("x", np.nan),
                gyroscope.get("y", np.nan),
                gyroscope.get("z", np.nan),
            ]
        )

    df_res = np.asarray(rows, dtype=np.float32)
    if df_res.size == 0:
        return None

    if np.isnan(df_res).any():
        for column_index in range(df_res.shape[1]):
            column = df_res[:, column_index]
            valid = column[~np.isnan(column)]
            fill_value = float(valid.mean()) if valid.size else 0.0
            column[np.isnan(column)] = fill_value
            df_res[:, column_index] = column

    relative_folder = file_path.parent.relative_to(DATASET_ROOT).as_posix().lower()
    label = 1 if relative_folder.startswith("fall -") else 0

    return {
        "data": df_res,
        "Label": label,
        "Activity": "fall" if label == 1 else "adl",
        "Subject": file_path.parent.name,
    }


def create_windows(
    data: np.ndarray, window_size: int = 32, overlap: int = 16
) -> np.ndarray:
    if len(data) < window_size:
        padded = np.repeat(data[-1:, :], window_size - len(data), axis=0)
        return np.asarray([np.vstack([data, padded])], dtype=np.float32)

    step = max(1, window_size - overlap)
    windows = []

    for i in range(0, len(data) - window_size + 1, step):
        windows.append(data[i : i + window_size])

    return np.asarray(windows, dtype=np.float32)


def extract_statistical_features(X_raw: np.ndarray) -> np.ndarray:
    features_list = []
    for window in X_raw:
        means = np.mean(window, axis=0)
        stds = np.std(window, axis=0)
        maxs = np.max(window, axis=0)
        mins = np.min(window, axis=0)
        smv = np.sqrt(np.sum(window[:, :3] ** 2, axis=1))
        smv_feat = [np.mean(smv), np.std(smv), np.max(smv)]

        row = np.hstack([means, stds, maxs, mins, smv_feat])
        features_list.append(row)

    return np.asarray(features_list, dtype=np.float32)


def plot_example_signals(all_data_list) -> None:
    fall_sample = next((item for item in all_data_list if item["Label"] == 1), None)
    adl_sample = next((item for item in all_data_list if item["Label"] == 0), None)

    if fall_sample is None or adl_sample is None:
        print("Không đủ mẫu ADL/Fall để vẽ biểu đồ.")
        return

    fig, (ax1, ax2) = plt.subplots(2, 1, figsize=(15, 10), sharex=True)

    ax1.plot(fall_sample["data"][:, :3])
    ax1.set_title("Tín hiệu TÉ NGÃ - 3 trục gia tốc")
    ax1.legend(["X", "Y", "Z"], loc="upper right")
    ax1.set_ylabel("Gia tốc (Raw)")

    ax2.plot(adl_sample["data"][:, :3])
    ax2.set_title("Tín hiệu BÌNH THƯỜNG (ADL) - 3 trục gia tốc")
    ax2.legend(["X", "Y", "Z"], loc="upper right")
    ax2.set_ylabel("Gia tốc (Raw)")
    ax2.set_xlabel("Số lượng mẫu (Samples)")

    plt.tight_layout()
    plt.show()


def export_to_onnx(model, num_features: int, output_dir: Path) -> None:
    try:
        from onnxmltools import convert_xgboost
        from onnxmltools.convert.common.data_types import FloatTensorType
    except Exception:
        print("Bỏ qua xuất ONNX vì thiếu onnxmltools.")
        return

    # For XGBoost conversion we need to specify target_opset for onnxconverter_common fallback
    initial_type = [("float_input", FloatTensorType([None, num_features]))]

    try:
        onnx_model = convert_xgboost(model, initial_types=initial_type, target_opset=9)
    except Exception:
        # Sometimes convert_xgboost internally expects the onnxconverter_common type despite what shape_calculator says
        try:
            from onnxconverter_common.data_types import (
                FloatTensorType as FloatTensorTypeCommon,
            )

            initial_type_common = [
                ("float_input", FloatTensorTypeCommon([None, num_features]))
            ]
            onnx_model = convert_xgboost(
                model, initial_types=initial_type_common, target_opset=9
            )
        except Exception as e:
            print(f"Lỗi xuất ONNX (cả 2 kiểu TensorType đều thất bại): {e}")
            return

    onnx_filename = output_dir / "fall_model.onnx"
    with onnx_filename.open("wb") as file:
        file.write(onnx_model.SerializeToString())

    print(f"Mô hình ONNX đã được lưu: {onnx_filename}")

    try:
        import onnxruntime as ort

        sess = ort.InferenceSession(str(onnx_filename))
        dummy_input = np.random.randn(1, num_features).astype(np.float32)
        input_name = sess.get_inputs()[0].name
        label_name = sess.get_outputs()[0].name
        prob_name = sess.get_outputs()[1].name
        prediction = sess.run([label_name, prob_name], {input_name: dummy_input})
        print("--- KIỂM TRA MODEL ONNX ---")
        print(f"Nhãn dự đoán giả lập: {prediction[0]}")
        print(f"Xác suất chi tiết: {prediction[1]}")
    except Exception:
        print("Đã lưu ONNX nhưng bỏ qua bước kiểm tra vì thiếu onnxruntime.")


# =========================
# Build samples
# =========================
all_file_paths = sorted(DATASET_ROOT.rglob("*.json"))
print(f"Tìm thấy {len(all_file_paths)} file JSON. Bắt đầu xử lý...")

results = [process_json_file(fp) for fp in tqdm(all_file_paths)]
all_data_list = [r for r in results if r is not None]

print(f"\nThành công: {len(all_data_list)}/{len(all_file_paths)} file.")

if all_data_list:
    print("\nVí dụ dữ liệu file đầu tiên sau khi xử lý:")
    print(all_data_list[0]["data"][:5])

plot_example_signals(all_data_list)


# =========================
# Create windows + labels
# =========================
all_windows_from_dfs = []
all_labels = []

for item in tqdm(all_data_list, desc="Đang tạo cửa sổ"):
    data = item["data"]
    windows_for_df = create_windows(data, window_size=WINDOW_SIZE, overlap=OVERLAP)

    if windows_for_df.size > 0:
        all_windows_from_dfs.append(windows_for_df)
        all_labels.append(np.full(len(windows_for_df), item["Label"], dtype=np.int64))

if all_windows_from_dfs:
    X_raw = np.vstack(all_windows_from_dfs)
    y = np.concatenate(all_labels)
else:
    X_raw = np.array([])
    y = np.array([])

if X_raw.size == 0:
    raise RuntimeError(
        "Không tạo được cửa sổ nào từ dataset. Kiểm tra lại WINDOW_SIZE/OVERLAP hoặc dữ liệu JSON."
    )

X = extract_statistical_features(X_raw)

print(f"\nTổng số mẫu (cửa sổ): {X.shape[0]}")
print(f"Số lượng đặc trưng mỗi mẫu: {X.shape[1]}")
print(f"Số lượng ADL: {(y == 0).sum()}")
print(f"Số lượng Fall: {(y == 1).sum()}")


# =========================
# Train and evaluate
# =========================
X_train, X_test, y_train, y_test = train_test_split(
    X,
    y,
    test_size=0.2,
    random_state=RANDOM_STATE,
    stratify=y,
)

xgb_model = XGBClassifier(
    n_estimators=300,
    random_state=RANDOM_STATE,
    n_jobs=-1,
    scale_pos_weight=(y_train == 0).sum() / (y_train == 1).sum()
    if (y_train == 1).sum() > 0
    else 1,
    eval_metric="logloss",
)

print("\nĐang huấn luyện mô hình... (vui lòng chờ)")
xgb_model.fit(X_train, y_train)

y_pred = xgb_model.predict(X_test)

print("\n--- KẾT QUẢ ĐÁNH GIÁ ---")
print(f"Độ chính xác (Accuracy): {accuracy_score(y_test, y_pred):.2%}")
print("\nBáo cáo chi tiết:")
print(
    classification_report(y_test, y_pred, target_names=["ADL", "Fall"], zero_division=0)
)
print("Ma trận nhầm lẫn:")
print(confusion_matrix(y_test, y_pred))


# =========================
# Save model
# =========================
OUTPUT_DIR.mkdir(parents=True, exist_ok=True)

model_filename = OUTPUT_DIR / "xgboost_fall_model.pkl"
joblib.dump(xgb_model, model_filename)

print(f"\nMô hình đã được lưu thành file: {model_filename}")

export_to_onnx(xgb_model, X.shape[1], OUTPUT_DIR)

"""# TESTTTTTTTTTTTTTTTT"""

from __future__ import annotations

import json
from pathlib import Path

import joblib
import matplotlib.pyplot as plt
import numpy as np
from sklearn.ensemble import GradientBoostingClassifier, RandomForestClassifier
from sklearn.metrics import accuracy_score, classification_report, confusion_matrix
from sklearn.model_selection import train_test_split
from sklearn.svm import SVC
from tqdm import tqdm
from xgboost import XGBClassifier

try:
    from google.colab import drive  # type: ignore

    IN_COLAB = True
except Exception:
    drive = None
    IN_COLAB = False


# =========================
# Colab setup
# =========================
def prepare_colab_environment() -> None:
    if not IN_COLAB:
        return

    try:
        drive.mount("/content/drive")
    except Exception:
        pass


if IN_COLAB:
    DATASET_ROOT = Path("/content/dataset/fall down mobile")  # Corrected path
    OUTPUT_DIR = Path("/content/drive/MyDrive/fally_artifacts")
else:
    BASE_DIR = Path(__file__).resolve().parent
    DATASET_ROOT = BASE_DIR / "dataset" / "fall down mobile"
    OUTPUT_DIR = BASE_DIR / "artifacts"

WINDOW_SIZE = 32
OVERLAP = 16
RANDOM_STATE = 42


# =========================
# Read dataset
# =========================
def process_json_file(file_path: Path):
    try:
        with file_path.open("r", encoding="utf-8") as file:
            payload = json.load(file)
    except Exception:
        return None

    sensors = payload.get("sensors", [])
    if not sensors:
        return None

    rows = []
    for sample in sensors:
        accelerometer = sample.get("accelerometer", {})
        gyroscope = sample.get("gyroscope", {})
        rows.append(
            [
                accelerometer.get("x", np.nan),
                accelerometer.get("y", np.nan),
                accelerometer.get("z", np.nan),
                gyroscope.get("x", np.nan),
                gyroscope.get("y", np.nan),
                gyroscope.get("z", np.nan),
            ]
        )

    df_res = np.asarray(rows, dtype=np.float32)
    if df_res.size == 0:
        return None

    if np.isnan(df_res).any():
        for column_index in range(df_res.shape[1]):
            column = df_res[:, column_index]
            valid = column[~np.isnan(column)]
            fill_value = float(valid.mean()) if valid.size else 0.0
            column[np.isnan(column)] = fill_value
            df_res[:, column_index] = column

    relative_folder = file_path.parent.relative_to(DATASET_ROOT).as_posix().lower()
    label = 1 if relative_folder.startswith("fall -") else 0

    return {
        "data": df_res,
        "Label": label,
        "Activity": "fall" if label == 1 else "adl",
        "Subject": file_path.parent.name,
    }


def create_windows(
    data: np.ndarray, window_size: int = 32, overlap: int = 16
) -> np.ndarray:
    if len(data) < window_size:
        padded = np.repeat(data[-1:, :], window_size - len(data), axis=0)
        return np.asarray([np.vstack([data, padded])], dtype=np.float32)

    step = max(1, window_size - overlap)
    windows = []

    for i in range(0, len(data) - window_size + 1, step):
        windows.append(data[i : i + window_size])

    return np.asarray(windows, dtype=np.float32)


def extract_statistical_features(X_raw: np.ndarray) -> np.ndarray:
    features_list = []
    for window in X_raw:
        means = np.mean(window, axis=0)
        stds = np.std(window, axis=0)
        maxs = np.max(window, axis=0)
        mins = np.min(window, axis=0)
        smv = np.sqrt(np.sum(window[:, :3] ** 2, axis=1))
        smv_feat = [np.mean(smv), np.std(smv), np.max(smv)]

        row = np.hstack([means, stds, maxs, mins, smv_feat])
        features_list.append(row)

    return np.asarray(features_list, dtype=np.float32)


def plot_example_signals(all_data_list) -> None:
    fall_sample = next((item for item in all_data_list if item["Label"] == 1), None)
    adl_sample = next((item for item in all_data_list if item["Label"] == 0), None)

    if fall_sample is None or adl_sample is None:
        print("Không đủ mẫu ADL/Fall để vẽ biểu đồ.")
        return

    fig, (ax1, ax2) = plt.subplots(2, 1, figsize=(15, 10), sharex=True)

    ax1.plot(fall_sample["data"][:, :3])
    ax1.set_title("Tín hiệu TÉ NGÃ - 3 trục gia tốc")
    ax1.legend(["X", "Y", "Z"], loc="upper right")
    ax1.set_ylabel("Gia tốc (Raw)")

    ax2.plot(adl_sample["data"][:, :3])
    ax2.set_title("Tín hiệu BÌNH THƯỜNG (ADL) - 3 trục gia tốc")
    ax2.legend(["X", "Y", "Z"], loc="upper right")
    ax2.set_ylabel("Gia tốc (Raw)")
    ax2.set_xlabel("Số lượng mẫu (Samples)")

    plt.tight_layout()
    plt.show()


def export_to_onnx(model, model_name: str, num_features: int, output_dir: Path) -> None:
    try:
        from onnxmltools import convert_xgboost
        from onnxmltools.convert.common.data_types import (
            FloatTensorType as FloatTensorTypeXGB,
        )
        from skl2onnx import convert_sklearn
        from skl2onnx.common.data_types import FloatTensorType
    except Exception:
        print("Bỏ qua xuất ONNX vì thiếu skl2onnx/onnxmltools.")
        return

    from xgboost import XGBClassifier

    if isinstance(model, XGBClassifier):
        try:
            initial_type = [("float_input", FloatTensorTypeXGB([None, num_features]))]
            try:
                onnx_model = convert_xgboost(
                    model, initial_types=initial_type, target_opset=9
                )
            except Exception:
                from onnxconverter_common.data_types import (
                    FloatTensorType as FloatTensorTypeCommon,
                )

                initial_type_common = [
                    ("float_input", FloatTensorTypeCommon([None, num_features]))
                ]
                onnx_model = convert_xgboost(
                    model, initial_types=initial_type_common, target_opset=9
                )

            onnx_filename = (
                output_dir
                / f"{model_name.lower().replace('classifier', '').strip()}_fall_model.onnx"
            )
            with onnx_filename.open("wb") as file:
                file.write(onnx_model.SerializeToString())
            print(f"Mô hình ONNX đã được lưu: {onnx_filename}")
        except Exception as e:
            print(f"Không thể xuất mô hình XGBoost sang ONNX: {e}")
            return
    elif isinstance(model, (RandomForestClassifier, GradientBoostingClassifier)) or (
        isinstance(model, SVC) and model.probability
    ):  # Check for SVC with probability enabled
        try:
            initial_type = [("float_input", FloatTensorType([None, num_features]))]
            onnx_model = convert_sklearn(
                model, initial_types=initial_type, target_opset=9
            )

            onnx_filename = (
                output_dir
                / f"{model_name.lower().replace('classifier', '').strip()}_fall_model.onnx"
            )
            with onnx_filename.open("wb") as file:
                file.write(onnx_model.SerializeToString())

            print(f"Mô hình ONNX đã được lưu: {onnx_filename}")

            try:
                import onnxruntime as ort

                sess = ort.InferenceSession(str(onnx_filename))
                dummy_input = np.random.randn(1, num_features).astype(np.float32)
                input_name = sess.get_inputs()[0].name
                label_name = sess.get_outputs()[0].name
                prob_name = sess.get_outputs()[1].name
                prediction = sess.run(
                    [label_name, prob_name], {input_name: dummy_input}
                )
                print("--- KIỂM TRA MODEL ONNX ---")
                print(f"Nhãn dự đoán giả lập: {prediction[0]}")
                print(f"Xác suất chi tiết: {prediction[1]}")
            except Exception:
                print("Đã lưu ONNX nhưng bỏ qua bước kiểm tra vì thiếu onnxruntime.")
        except Exception as e:
            print(f"Không thể xuất mô hình {model_name} sang ONNX: {e}")
    else:
        print(
            f"Bỏ qua xuất ONNX cho mô hình {model_name} (không hỗ trợ hoặc không có thuộc tính xác suất)."
        )


# =========================
# Build samples
# =========================
all_file_paths = sorted(DATASET_ROOT.rglob("*.json"))
print(f"Tìm thấy {len(all_file_paths)} file JSON. Bắt đầu xử lý...")

results = [process_json_file(fp) for fp in tqdm(all_file_paths)]
all_data_list = [r for r in results if r is not None]

print(f"\nThành công: {len(all_data_list)}/{len(all_file_paths)} file.")

if all_data_list:
    print("\nVí dụ dữ liệu file đầu tiên sau khi xử lý:")
    print(all_data_list[0]["data"][:5])

plot_example_signals(all_data_list)


# =========================
# Create windows + labels
# =========================
all_windows_from_dfs = []
all_labels = []

for item in tqdm(all_data_list, desc="Đang tạo cửa sổ"):
    data = item["data"]
    windows_for_df = create_windows(data, window_size=WINDOW_SIZE, overlap=OVERLAP)

    if windows_for_df.size > 0:
        all_windows_from_dfs.append(windows_for_df)
        all_labels.append(np.full(len(windows_for_df), item["Label"], dtype=np.int64))

if all_windows_from_dfs:
    X_raw = np.vstack(all_windows_from_dfs)
    y = np.concatenate(all_labels)
else:
    X_raw = np.array([])
    y = np.array([])

if X_raw.size == 0:
    raise RuntimeError(
        "Không tạo được cửa sổ nào từ dataset. Kiểm tra lại WINDOW_SIZE/OVERLAP hoặc dữ liệu JSON."
    )

X = extract_statistical_features(X_raw)

print(f"\nTổng số mẫu (cửa sổ): {X.shape[0]}")
print(f"Số lượng đặc trưng mỗi mẫu: {X.shape[1]}")
print(f"Số lượng ADL: {(y == 0).sum()}")
print(f"Số lượng Fall: {(y == 1).sum()}")


# =========================
# Train and evaluate different models
# =========================
X_train, X_test, y_train, y_test = train_test_split(
    X,
    y,
    test_size=0.2,
    random_state=RANDOM_STATE,
    stratify=y,
)

models = {
    "XGBClassifier": XGBClassifier(
        n_estimators=300,
        random_state=RANDOM_STATE,
        n_jobs=-1,
        scale_pos_weight=(y == 0).sum() / (y == 1).sum() if (y == 1).sum() > 0 else 1,
        eval_metric="logloss",
    ),
    "RandomForestClassifier": RandomForestClassifier(
        n_estimators=300,
        random_state=RANDOM_STATE,
        n_jobs=-1,
        class_weight="balanced_subsample",
    ),
    "GradientBoostingClassifier": GradientBoostingClassifier(
        n_estimators=100,
        random_state=RANDOM_STATE,
    ),
    "SVC": SVC(
        random_state=RANDOM_STATE,
        class_weight="balanced",
        probability=True,  # Required for ONNX export if probability output is needed
    ),
}

best_model_name = None
best_fall_recall = -1
best_model = None

for name, model in models.items():
    print(f"\n--- Đang huấn luyện mô hình: {name} ---")
    model.fit(X_train, y_train)
    y_pred = model.predict(X_test)

    print(f"\n--- KẾT QUẢ ĐÁNH GIÁ CỦA {name} ---")
    print(f"Độ chính xác (Accuracy): {accuracy_score(y_test, y_pred):.2%}")
    report = classification_report(
        y_test, y_pred, target_names=["ADL", "Fall"], output_dict=True, zero_division=0
    )
    print("\nBáo cáo chi tiết:")
    print(
        classification_report(
            y_test, y_pred, target_names=["ADL", "Fall"], zero_division=0
        )
    )
    print("Ma trận nhầm lẫn:")
    print(confusion_matrix(y_test, y_pred))

    fall_recall = report["Fall"]["recall"]
    if fall_recall > best_fall_recall:
        best_fall_recall = fall_recall
        best_model_name = name
        best_model = model

print(
    f"\nModel tốt nhất dựa trên Recall của Fall: {best_model_name} với recall là {best_fall_recall:.2f}"
)

# =========================
# Save model
# =========================
OUTPUT_DIR.mkdir(parents=True, exist_ok=True)

if best_model is not None and best_model_name is not None:
    model_filename = (
        OUTPUT_DIR
        / f"{best_model_name.lower().replace('classifier', '').strip()}_fall_model.pkl"
    )
    joblib.dump(best_model, model_filename)
    print(
        f"\nMô hình tốt nhất ({best_model_name}) đã được lưu thành file: {model_filename}"
    )

    # Export the best model to ONNX
    export_to_onnx(best_model, best_model_name, X.shape[1], OUTPUT_DIR)
else:
    print("Không tìm thấy mô hình tốt nhất để lưu.")
