# -*- coding: utf-8 -*-
"""Fally_CCTV.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1hj8p3lhVUAgny_kRd2ayuYVEdBtRon3w

# Init & setup account
"""

!pip install ultralytics
import ultralytics
ultralytics.checks()

from google.colab import files
files.upload() # Chọn file kaggle.json từ máy tính của bạn

# Cấu hình thư mục chứa token bảo mật
!mkdir -p ~/.kaggle
!cp kaggle.json ~/.kaggle/
!chmod 600 ~/.kaggle/kaggle.json

# Tải xuống và giải nén bộ dữ liệu Phát hiện ngã (Fall Detection Dataset)
!kaggle datasets download -d uttejkumarkandagatla/fall-detection-dataset
!unzip -q fall-detection-dataset.zip -d /content/fall_detection_data

"""# Config Dataset"""

import yaml

data_config = {
    'train': '/content/fall_detection_data/images/train',
    'val': '/content/fall_detection_data/images/Val',
    'nc': 3,
    'names': ['Fall Detected', 'Walking', 'Sitting']
}

with open('/content/data.yaml', 'w') as f:
    yaml.dump(data_config, f, default_flow_style=False)

print("Đã tạo file data.yaml thành công!")

import os
import yaml

# 1. Tự động kiểm tra các thư mục đang có trong dữ liệu đã giải nén
base_path = '/content/fall_detection_data'
subfolders = os.listdir(base_path)
print("Các thư mục gốc tìm thấy:", subfolders)

# Thử tìm thư mục con chứa ảnh (thường là 'images' hoặc 'Fall Detection Dataset')
if 'images' in subfolders:
    img_dir = os.path.join(base_path, 'images')
else:
    # Tìm thư mục lồng bên trong nếu cấu trúc giải nén bị đổi
    img_dir = os.path.join(base_path, subfolders[0], 'images') if os.path.isdir(os.path.join(base_path, subfolders[0])) else base_path

# Liệt kê chính xác tên thư mục train/val bên trong
if os.path.exists(img_dir):
    inner_folders = os.listdir(img_dir)
    print("Các thư mục bên trong thư mục ảnh:", inner_folders)

    # Định dạng lại tên cho đúng chữ hoa/chữ thường thực tế
    train_folder = 'train' if 'train' in inner_folders else ('Train' if 'Train' in inner_folders else inner_folders[0])
    val_folder = 'val' if 'val' in inner_folders else ('Val' if 'Val' in inner_folders else ('validation' if 'validation' in inner_folders else inner_folders[1]))

    train_path = os.path.join(img_dir, train_folder)
    val_path = os.path.join(img_dir, val_folder)
else:
    # Trường hợp dataset không gom cụm vào thư mục 'images'
    train_path = f"{base_path}/train"
    val_path = f"{base_path}/val"

# 2. Ghi đè lại file data.yaml với đường dẫn tuyệt đối chính xác
data_config = {
    'train': train_path,
    'val': val_path,
    'nc': 3,
    'names': ['Fall Detected', 'Walking', 'Sitting']
}

with open('/content/data.yaml', 'w') as f:
    yaml.dump(data_config, f, default_flow_style=False)

print("\n--- Cấu hình mới trong file data.yaml ---")
print(f"Đường dẫn Train: {train_path}")
print(f"Đường dẫn Val: {val_path}")

"""# Train model"""

from ultralytics import YOLO

# 1. Khởi tạo mô hình YOLOv8 Nano (Pre-trained)
model = YOLO('yolov8n.pt')

# 2. Tiến hành huấn luyện bằng hàm .train() của Python API
results = model.train(
    data='/content/data.yaml',   # Đường dẫn tới file cấu hình dữ liệu
    epochs=50,                  # Số lượt chạy huấn luyện
    imgsz=640,                  # Kích thước ảnh đầu vào
    batch=16,                   # Kích thước gói dữ liệu cho mỗi bước lặp
    device=0,                   # Sử dụng GPU đầu tiên (cuda:0)
    workers=4,                  # Số luồng CPU dùng để tải dữ liệu song song
    save=True                   # Tự động lưu lại các checkpoint và trọng số tốt nhất
)

from google.colab import files
files.download('/content/runs/detect/train-2/weights/best.pt')

"""# Put video to test"""

import os
from google.colab import files
from ultralytics import YOLO

# 1. Tạo khu vực upload file video từ máy tính của bạn
print("Vui lòng chọn file video (.mp4, .avi, .mov) cần nhận diện:")
uploaded = files.upload()

# 2. Tự động lấy tên file video vừa được tải lên thành công
video_path = list(uploaded.keys())[0]
print(f"\n Đã tải lên thành công file: {video_path}")

# 3. Tải mô hình YOLOv8 bạn vừa huấn luyện xong
model = YOLO('/content/runs/detect/train-2/weights/best.pt')

# 4. Tiến hành chạy nhận diện (Predict) trên video vừa tải
print("\n Đang tiến hành xử lý nhận diện hành động trên video...")
results = model.predict(
    source=video_path,
    conf=0.40,       # Ngưỡng tin cậy 40% để giảm thiểu lỗi nhận diện sai
    save=True        # Lưu lại video đã vẽ khung bounding box
)

# 5. Xác định thư mục lưu trữ video đầu ra
# YOLOv8 tự động tạo thư mục predict tăng dần (predict, predict2,...)
latest_predict_dir = model.predictor.save_dir
output_video_path = os.path.join(latest_predict_dir, video_path)

print(f"\n Hoàn tất! Video kết quả nhận diện đã được lưu tại: {output_video_path}")